### ISSUE TITLE
Composer won't find 1.6.1

### ISSUE THREAD

**Issue by klickreflex** [jackabox/statamic-shopify#102]
Despite a release being tagged for 1.6.1 and shown in the CP I can't update from 1.6.0 to 1.6.1:
>  Could not find package jackabox/statamic-shopify in a version matching "1.6.1" and a stability matching "dev".

**Comment by jackabox** [comment]
1.6.1 wasn't to be released sorry, it was a testing ground for fixing an issue with duplicate images which ended up being an `.env` variable error.
