### ISSUE TITLE
CP Dashboard always shows "Set Things Up" section with new Admin Token

### ISSUE THREAD

**Issue by grandpalacko** [jackabox/statamic-shopify#118]
Even if Admin Token is set for new Shopify apps, the Dashboard in CP always shows the "Set Things Up" section and the Import functionality is never visible.

The problem comes from the check for "can run import", it never checks for the existence of the Admin Token:
https://github.com/jackabox/statamic-shopify/blob/4e47e20a30ff7e28391973c238615f69c3799613/src/Http/Controllers/CP/DashboardController.php#L18

**Comment by jackabox** [comment]
Thanks, It's on my list to fix and should be patched in the next day or two. Also flagged in #115. 

For now, please use the command line.
