### ISSUE TITLE
Class Jackabox\Shopify\Http\Controllers\Api\VariantsController located in ./vendor/jackabox/statamic-shopify/src/Http/Controllers/Actions/VariantsController.php does not comply with psr-4 autoloading standard. Skipping.

### ISSUE THREAD

**Issue by philpasquin** [jackabox/statamic-shopify#13]
When running ```composer require jackabox/statamic-shopify``` we get this error ```Class Jackabox\Shopify\Http\Controllers\Api\VariantsController located in ./vendor/jackabox/statamic-shopify/src/Http/Controllers/Actions/VariantsController.php does not comply with psr-4 autoloading standard. Skipping.```

Which reflects to an error when trying to create a new product ``` Error
Call to undefined method Statamic\Entries\Collection::slug()```

**Comment by jackabox** [comment]
What's the steps to reproduce this? 

These are two different areas that shouldn't interact. Creating a product doesn't touch the action. 

Are you creating the product in Statamic rather than importing it?

**Comment by jackabox** [comment]
@philpasquin caught it, there was an error on the new product collection with variants field. The plugin works with us ideally creating the products in Shopify otherwise you won't have the data linked to send it to the cart later on.
