### ISSUE TITLE
Changing SEO slug in Shopify duplicates product 

### ISSUE THREAD

**Issue by jensolafkoch** [jackabox/statamic-shopify#135]
(Version 1.7.6)

We observed that any time we change the URL handle for a product in Shopify in the SEO section, on next import we get a duplicated product in Statamic instead of an updated slug in the original entry. 

Changes in Shopify were made here in the latest input (German UI) of a product entry, called "URL-Handle":

![shopify-seo](https://user-images.githubusercontent.com/47628003/187079062-a74ccbd3-c87f-48a8-a4b5-f062cf41a240.png)

**Comment by Pixney-William** [comment]
I am finding that i also have duplicated products on import. I also use 1.7.6 and will start looking into this a bit now. Thought i would make a comment just to make sure we are aware others also experience this.

**Comment by Pixney-William** [comment]
Scenario:

1. In shopify with the same title "william". I import these, and that works fine.
2. Slug of one product is `william` and slug of second product is `william-1`
3. Change `william.-1` to `william-juice`
4. Import all products
5. You can see 3 products in your list. Where one has the slug of `william-1`

**Comment by jackabox** [comment]
Hey both, apologies for any delay in getting back in response - I've been on vacation over the last month.

Products are currently imported based on matching the slug, so this would identify as a new product at the moment. This will need an adjustment to query products where they have the unique ID assigned to them but is a bit more complex in terms of querying the fields. I will action this as soon as possible.

**Comment by Pixney-William** [comment]
Sounds great @jackabox

**Comment by jensolafkoch** [comment]
Great news, very much looking forward! @jackabox

**Comment by nutsandbananas** [comment]
@jackabox We have a client experiencing a lot of problem with this so just checking what the status on this issue is or if someone else has a solution for it?

**Comment by jackabox** [comment]
Hey apologies for the delay. I’ll handle it as soon as possible I’ve just had a few other things take over.

**Comment by jensolafkoch** [comment]
@jackabox 

We checked the new version and the effect is now that any change in the URL handle of a Shopify product is **not** reflected in Statamic after re-importing the product. 

Do I miss something here?

**Comment by jackabox** [comment]
@jensolafkoch The URL is not currently updated in Statamic on re-import as the Statamic source is treated as the truth in terms of SEO. Since this will be the front face of the website and where the pages are handled.

For v2, this may change but it would break backwards compatibility at the moment.
