### ISSUE TITLE
Importing product without an image fails.

### ISSUE THREAD

**Issue by Pixney-William** [jackabox/statamic-shopify#18]
I created a test product and had not added an image when tried to import all products. An exception was thrown:
`Argument 1 passed to Jackabox\Shopify\Jobs\ImportSingleProductJob::importImages() must be of the type array, null given, called in /Users/pixney/Development/Repos/statamic/vendor/jackabox/statamic-shopify/src/Jobs/ImportSingleProductJob.php on line 79`

![image](https://user-images.githubusercontent.com/31292231/111508883-77aca700-874c-11eb-9a8f-092ac5b17aed.png)

**Comment by jackabox** [comment]
Should be fixed on v1.1.2, thanks for flagging :)
