### ISSUE TITLE
[Feature] Allow the user to pull in collections

### ISSUE THREAD

**Issue by jackabox** [jackabox/statamic-shopify#24]
**Reasoning**

Allow users to sync collections as recommended by discussion #22. This would help to build dynamic collections within Shopify and then import them.

**Changes Required**

- New collection sync to import to Statamic Collections.
- New dashboard interaction.
- Needs to be completely optional as users may or may not want this.

**Comment by edalzell** [comment]
Please note that a product can be in more than one collection, so the field (assuming you do it as a taxonomy) should likely be named `collections` and be an array
