### ISSUE TITLE
[Docs] Webhooks - Product Update endpoint looks incorrect?

### ISSUE THREAD

**Issue by sebszocinski** [jackabox/statamic-shopify#28]
Hey, me again!

Just setting up and testing webhooks for product creation/update and noticed the [docs for product update](https://statamic-shopify.jackwhiting.co.uk/CMS/webhooks#product-update) say to use the `/webhook/product/create` endpoint. I checked the source routes in `action.php` and noticed there is an endpoint for `/webhook/product/update`, .

I know you only just added this feature last week so you might have just forgot to update this one?

**Comment by jackabox** [comment]
On version 1.2. There are a few endpoints

- Create for new products
- Update for updating products
- Delete for deleting products 

[webhooks doc](https://statamic-shopify.jackwhiting.co.uk/CMS/webhooks)

**Comment by sebszocinski** [comment]
Hey Jack. Yep I'm aware and they are working well but the docs need to be updated. See below:

![image](https://user-images.githubusercontent.com/5466694/113476917-07c94b00-94c6-11eb-9036-7647f2564c5e.jpeg)

**Comment by jackabox** [comment]
I see what you are saying now. Thank you. :)
