### ISSUE TITLE
Variant option name missing / not being imported

### ISSUE THREAD

**Issue by sebszocinski** [jackabox/statamic-shopify#31]
Just noticed it doesn't look like the option name isn't being synced across.

See below, in this case "Painting" is missing. In our case we want to display this.

![image](https://user-images.githubusercontent.com/5466694/113526832-a3f46e80-95fa-11eb-8c9e-540508986d9b.png)

**Comment by jackabox** [comment]
Added this as in 1.3.0

Please see the release notes for [1.3.0](https://github.com/jackabox/statamic-shopify/releases/tag/1.3.0) as you'll need to configure your blueprint slightly.
