### ISSUE TITLE
Configured currency not used in Cart 

### ISSUE THREAD

**Issue by klickreflex** [jackabox/statamic-shopify#34]
Hi,

I've configured `'currency' => '€',` and this works on the Products template, but the cart still shows product prices as `£`. Is this possibly still hard coded somewhere?

**Comment by jackabox** [comment]
Config value works for anything done on the PHP/admin side.

For the cart, it uses the frontend js.

You'll need to edit the `formatCurrency` function in the [`helpers.js`](https://github.com/jackabox/statamic-shopify/blob/e038455e0ac913ac033e6f4224b721e86969720c/resources/js/shopify/helpers.js#L54)

**Comment by klickreflex** [comment]
Thank you 👍
