### ISSUE TITLE
Collections import doesn't import all my collections

### ISSUE THREAD

**Issue by austriker27** [jackabox/statamic-shopify#64]
Hey Jack! 

I might have done something wrong but wanted to open this issue in case there's a chance there's a bug. 

Here's what I did:
1. I updated the Shopify addon to the latest (1.4.2) 
2. Ran `php artisan shopify:import:collections` in the CLI
3. ran `php artisan vendor:publish --provider="Jackabox\Shopify\ServiceProvider"` in CLI
4. Cleared the stache cache just in case

I got a gazillion changes in `content/collections/products`  which seems expected because it created my products in that folder. 
I also got a gazillion changes in `content/collections/variants/`... 
If these content additions are expected behavior then great! I have 100 products and 312 variants so I wasn't expected them all to be replicated in collections. 

When I navigate to the `taxonomies > Product Collections`, I see only 1:
![image](https://user-images.githubusercontent.com/14855925/120327578-c32c1700-c29e-11eb-9be6-6d12cc3aed4b.png)

However here's what I've got in the shopify admin panel:
![image](https://user-images.githubusercontent.com/14855925/120327642-d808aa80-c29e-11eb-869d-5317558cef50.png)

NOTE: I missed this step: `You'll need to publish the assets or create a new taxonomy for them in the admin panel. ` that's listed in the update readme, however it seems like the import created that taxonomy. 🤔 I can delete all the `collections` and start over if you think that would help. 

Are there any other reasons why the collections import would have missed collections? 

Thanks!  

Versions:
Statamic: 3.1.18
Shopify addon: 1.4.2
PHP: 7.4

**Comment by jackabox** [comment]
Hey,

Do you have products in those collections?

Try re-run the import now you have the collection taxonomy.

None of your data should be replicated in a collection, odd that your variants would update but if you haven't synced in a while it would also be updating the "sale price" field, which would cause differences. Can you let me know what changed on a **product** and a **variant**? 

The changes to your products are expected, it should assign the collections to the product itself (as a taxonomy). Do you have a product you know is in a collection that you can verify gets the collection data?

**Comment by austriker27** [comment]
Heyo,

Yes, I can confirm each collection has active products. Basically when I migrated my data from Woocommerce to shopify it looks like it turned the WC product categories into collections (just an FYI in case that helps to know how Im using them, although I would still be using them for certain item groups if my data migration was perfect):
![image](https://user-images.githubusercontent.com/14855925/120329092-59ad0800-c2a0-11eb-9e2c-82b2f92e5b42.png)

I've re-ran the import via the CP and CLI but haven't got new product collections imported. (I also cleared the statamic/stache cache and browser cache again for good measure)

I think you are right, from looking at the files, the `content/collections/products/product_name.md` updates looks like its not related to the collections import itself. Here's one example:
![image](https://user-images.githubusercontent.com/14855925/120329780-08514880-c2a1-11eb-8b62-2a8da0883b81.png)

example for `content/collections/variant/variant_id.md`:
![image](https://user-images.githubusercontent.com/14855925/120329904-274fda80-c2a1-11eb-9980-72cb7bac4974.png)

I found this item which is in a collection in shopify but doesnt have anything related to that in statamic:
![image](https://user-images.githubusercontent.com/14855925/120330440-ad6c2100-c2a1-11eb-977b-1f40cb4a504f.png)

`content/collections/products/5-panel-logo-camper-hat.md`: 
![image](https://user-images.githubusercontent.com/14855925/120330549-c4ab0e80-c2a1-11eb-8cca-c9ffc6a52420.png)

That md file should show a taxonomy of `product_collection: hat` right?

**Comment by jackabox** [comment]
What's the taxonomy slug of your "collections", is it `product_collection`?

Set this .env to match it `SHOPIFY_TAXONOMY_COLLECTIONS`

If you import the product again, does it work? 

There is a check in the code to see if the collection exists, if not, it skips loading the collection data so maybe something here.

**Comment by austriker27** [comment]
Oo I didnt know about that `env` value... Sorry taxonomies always are the thing that confuse me the most, so maybe I reading this wrong but looks like there's no slug set:

Looks like there's no slug set - under `content/taxonomies/collections.yaml` the file only has this:
```
title: 'Product Collections'
```

And i haven't created any view files for it in `resources/views` yet

![image](https://user-images.githubusercontent.com/14855925/120332927-0dfc5d80-c2a4-11eb-82e4-37fc42cea0ed.png)

**Comment by jackabox** [comment]
What's the file name? The slug matches that.

**Comment by austriker27** [comment]
> What's the file name? The slug matches that.
> 
> So if it's `product_collections` that isn't the default and will ignore it. This might be just the way that the taxonomy was created.

Interesting, the filename is `collections.yaml`

**Comment by austriker27** [comment]
> 
> If you import the product again, does it work?
> 

I'll try re-importing a few products that have collections.

**Comment by jackabox** [comment]
> > If you import the product again, does it work?
> 
> I'll try re-importing a few products that have collections.

Let me know if that fails, `collections` is the default so you shouldn't need the env param

**Comment by austriker27** [comment]
> > > If you import the product again, does it work?
> > 
> > 
> > I'll try re-importing a few products that have collections.
> 
> Let me know if that fails, `collections` is the default so you shouldn't need the env param

Shoot, after importing 2 products that have collections its not appearing on their markdown files. Here's a screenshot showing the changes for one file: 
![image](https://user-images.githubusercontent.com/14855925/120480551-056b5c00-c364-11eb-8447-05437fc616af.png)

**Comment by jackabox** [comment]
When you run the import, do either of these jobs trigger?

```
[2021-06-02 13:17:52][31e64c3b-21a8-46db-9bcb-537d8fb0ddd1] Processed:  Jackabox\Shopify\Jobs\FetchCollectionsForProductJob
[2021-06-02 13:17:52][96a2a3ad-fc24-47ed-8b6e-b091ad1b132d] Processing: Jackabox\Shopify\Jobs\ImportCollectionsForProductJob
```

**Comment by jackabox** [comment]
@austriker27 Are the collections the products included in automated, or manual? Might be an issue with automated by the looks of things.

**Comment by austriker27** [comment]
> @austriker27 Are the collections the products included in automated, or manual? Might be an issue with automated by the looks of things.

Good find, I think you might be right. Looks like all my auto collections didnt migrate but the "home page", which isnt auto, did.

**Comment by jackabox** [comment]
@austriker27 Can you updated it to 1.4.3 and let me know if this fixes it? If not, reopen this :)

**Comment by austriker27** [comment]
Shoot, its not working for me. I updated the addon to 1.4.3, re-ran the collections import (via the PHP command in the CLI and in the CP), and re-imported 2 products that have smart collections. I also cleared the statamic cache for good measure. Anything else I can try or any details I can provide?
