### ISSUE TITLE
Sync Shopify from Statamic?

### ISSUE THREAD

**Issue by hmalaud** [jackabox/statamic-shopify#68]
Would it be possible to sync changes from Statamic's collections to update Shopify products so that user can avoid using Shopify as much as possible or is Shopify's admin completely closed?

**Comment by jackabox** [comment]
It's possible to do, you can create, update, and delete as needed. 

However relatively outside of the scope for this at the moment, as the UI for the product update/edit/etc is much more refined being managed through the Shopify side than through Statamic. It'd be a huge chunk of work to do at this time.

**Comment by hmalaud** [comment]
Ok, thanks for the answer!

**Comment by jackabox** [comment]
Feel free to open a discussion for it though, more than happy to consider if enough people want 👍🏻
