### ISSUE TITLE
Call to a member function handle() on null

### ISSUE THREAD

**Issue by Pixney-William** [jackabox/statamic-shopify#73]
Just a quick question if you have ever seen this error when importing products? 

`'blueprint' => $this->blueprint()->handle(),` is the line it errors on.

exception: "Error"
file: "/Users/pixney/Development/Web/uf/vendor/statamic/cms/src/Entries/Entry.php"
line: 449
message: "Call to a member function handle() on null"

**Comment by Pixney-William** [comment]
Seems to be the variants:

```

#id: "34348192-68a1-4ecf-853c-96a157323433"
  #collection: "variants"
  #blueprint: null
```

**Comment by jackabox** [comment]
See #67
