### ISSUE TITLE
Products marked as draft are imported and shown in the front-end

### ISSUE THREAD

**Issue by francoismajor** [jackabox/statamic-shopify#75]
In Shopify, when you create a product, by default it's set to draft.

When importing all products, the  draft product is imported anyways and shows up on the website, but won't do anything when you add it to your cart (as the product is not active).

**Best case**
Product is imported but unpublished.

**Min case**
Product is skipped and not imported.

**Comment by jackabox** [comment]
Good catch, should be able to get this off `status`, and mark it as published or not.

**Comment by jackabox** [comment]
Added in 1.5.0. Let me know if you have any issues :)

**Comment by francoismajor** [comment]
Awesome, I'll give it a try this week, thanks!

**Comment by francoismajor** [comment]
It works! Thanks
