### ISSUE TITLE
Inventory quantity below 0 doesn't list as out of stock

### ISSUE THREAD

**Issue by austriker27** [jackabox/statamic-shopify#81]
Hello! 

I think I found a bug with inventory that's below 0. (I have some inventory that's negative numbers). 

here's what the variant shows for this product: 

```
product_slug: retro-tee
title: XS
inventory_quantity: -1
```

And Im using this loop from the docs:
`{{ product_variants:generate :product="slug" show_price="true" show_out_of_stock="false" class="border" }}`
(it also shows the XS size which is out of stock if I use `show_out_of_stock="false" `)

Screenshot of the frontend:
![image](https://user-images.githubusercontent.com/14855925/129495685-35ffe324-2b5f-4184-97bf-ece12922f513.png)

**Comment by jackabox** [comment]
What's setting the stock as `-1` here?

**Comment by austriker27** [comment]
Shopify - I often have products that are in the negative numbers as I juggle inventory between multiple locations. Its odd but it happens.

**Comment by jackabox** [comment]
Should be sorted in 1.5.2, there's now a check for if `<= 0` rather than `=== 0`

**Comment by austriker27** [comment]
> Should be sorted in 1.5.2, there's now a check for if `<= 0` rather than `=== 0`

Nice, thanks!
