### ISSUE TITLE
FR: Import shipping costs from Shopify

### ISSUE THREAD

**Issue by austriker27** [jackabox/statamic-shopify#82]
I'm not sure if this is possible based on the shopify API's but I think it would be super helpful to be able to display shipping costs on the cart page.

Here's an example: 
![image](https://user-images.githubusercontent.com/14855925/130064553-2fa98414-ce87-40f3-9398-b469c0daa2c4.png)

**Comment by jackabox** [comment]
At this point in the checkout, you don't have any information of the user (delivery address, speed, etc) so there isn't much point in capturing it at this point in the plugin.

However, you could look at this [API](https://shopify.dev/api/storefront/reference/checkouts/availableshippingrates#shippingrates-2021-07) to grab the available shipping rates.
