### ISSUE TITLE
Bug: The "Go To Shopify Admin" cannot handle a https:// prepended URL in the .env

### ISSUE THREAD

**Issue by el-schneider** [jackabox/statamic-shopify#87]
This button doesn't work properly, but probably should:

<img width="317" alt="grafik" src="https://user-images.githubusercontent.com/26460248/131961326-5c5d18ef-36eb-498b-8af4-0a44b2077deb.png">

```env
# this works
SHOPIFY_APP_URL=some-shop.myshopify.com

# this does not
SHOPIFY_APP_URL=https://some-shop.myshopify.com
```

## Setup
Statamic 3.2.1 Pro
Laravel 8.58.0
PHP 7.4.22
jackabox/statamic-shopify 1.5.2

**Comment by jackabox** [comment]
It's not meant to have a prepended `https`. See [](https://statamic-shopify.jackwhiting.co.uk/env#required-for-admin)
