### ISSUE TITLE
Sorting the variants dropdown alphabetically

### ISSUE THREAD

**Issue by mnlmaier** [jackabox/statamic-shopify#88]
Hello, is there a possibility to sort the variants dropdown alphabetically? Should probably be doable in `parseOptions` of the `ProductVariants` class, am I missing something here? :)

**Comment by jackabox** [comment]
At the moment, there is not out of the box. 

You could loop around the variants field (statamic relationship field) and then fetch each by [title](https://github.com/jackabox/statamic-shopify/blob/main/src/Tags/ProductVariants.php#L64).

**Comment by jackabox** [comment]
ProductVariants can be overwritten as I've changed the scope in v1.7.6 (#129).
