### ISSUE TITLE
Out of Stock status for products that are not inventory managed

### ISSUE THREAD

**Issue by richarderoche** [jackabox/statamic-shopify#89]
Is there a way to check if stock is applicable before checking inventory of a product? I have a client that delivers made-to-order meals so inventory tracking doesn't make sense. We could just put in a large number as a workaround, but we also want to sell gift cards which don't even have the option to set an inventory in Shopify.

**Comment by jackabox** [comment]
If they are not inventory managed then the system will not know if they are in stock/out of stock. The checks in place are;

- if it is inventory managed (toggle from Shopify)
- if so, does it have stock.
- else, show as in stock.

**Comment by richarderoche** [comment]
What would you suggest I do to make it possible to sell gift cards? They show as sold out and are not purchase-able. I'm sure I can modify your add-on but then I can't update it automatically. Would it make sense in a future update to assume products are sellable unless it is inventory managed AND out of inventory?

**Comment by jackabox** [comment]
Hey @richarderoche, can you send me one of the variant markdown files for the variants that should be showing as "in stock" and are not inventory managed? Along with that can you send me a screenshot of your setup in Shopify?

Sounds like a bug with either how the data is set up or how it's importing as this [line on the tag](https://github.com/jackabox/statamic-shopify/blob/main/src/Tags/ProductVariants.php#L117) is checking for if deny is there.

**Comment by richarderoche** [comment]
I poked around a bit, I don't think it's an import issue. I queried the api directly and it seems like all the values match. Looks like inventory_policy is set to "deny" by default when you make a new product in Shopify. I can turn on tracking and change it to "continue" by checking the option to sell when it's sold out but I think the property will always be set. I think you want to import the inventory_management property and check if that is set [here](https://github.com/jackabox/statamic-shopify/blob/d2e2fad21e8e5c53ff1281e13a02222c85090e81/src/Tags/ProductVariants.php#L116) instead. I'm not an expert though, perhaps I'm missing something.

**Comment by jackabox** [comment]
The `inventory_policy` is what Shopify uses to define if a product should be tracked/sell out of stock. If this is set to allow, it'll always be allowed to sell.

Can you please show me the content file for a variant/screenshots of your Shopify set-up for the same variants so I can reproduce it?

**Comment by richarderoche** [comment]
Screenshot of settings:

![thespicyradish myshopify com_admin_products_7202080555177](https://user-images.githubusercontent.com/5722728/133147597-830d622e-b895-44f9-b299-51067777ecef.png)

The content file for the variant:
[41268858486953.md](https://github.com/jackabox/statamic-shopify/files/7157027/41268858486953.md)

Here's what the API call shows:
![image](https://user-images.githubusercontent.com/5722728/133147701-825d1aaa-d051-4dd1-9c81-39f8bd96bd00.png)

So basically it shows that if you do not want inventory tracking, it leaves "inventory_management" as null but "inventory_policy" is set to "deny" by default so it can't be used to determine if we want to track to begin with.

You can reproduce by setting up your starter shop, creating an active product and leaving the inventory tracking unchecked. When you import it will display as sold out on your statamic front end but will have the expected result of being available for purchase on the hosted shopify storefront.

**Comment by jackabox** [comment]
Closed in v1.6.0, we now checked `inventory_management`.
