### ISSUE TITLE
How to localize price format?

### ISSUE THREAD

**Issue by klickreflex** [jackabox/statamic-shopify#96]
`product_price` always renders `€20.00`, but I need it to be `20,00 €`. 

If it's not possible to change the tags format, is there a way to just get the raw number into templates?

**Comment by klickreflex** [comment]
Luckily I don't need variants so I'm working around by doing the following on product listings
```
{{ product_variants:from_index index="0" }}
    {{ price format_number="2|,|." }} €
{{ /product_variants:from_index }}
```

**Comment by jackabox** [comment]
Would welcome an update to allow for different currency formatting, otherwise you can disable the currency symbol being added and loop around variants to output the prices as needed.
